// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Botresponse(arg1) {
  return window['go']['main']['App']['Botresponse'](arg1);
}

export function CollectAPI(arg1) {
  return window['go']['main']['App']['CollectAPI'](arg1);
}
