// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Botresponse(arg1:string):Promise<string>;

export function CollectAPI(arg1:string):Promise<string>;
